spring.application.name=rachapro-backend

spring.datasource.url=${RACHAPRO_DB_URL}
spring.datasource.username=${RACHAPRO_DB_USER}
spring.datasource.password=${RACHAPRO_DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always